Task 4 feed back and Task5
asazycat/ncNews pull request #3
Opened 2023-07-19 10:09 UTC by asazycat

I applied the feedback from my previous pull onto task 5 and did task 5 as well

2023-07-19 11:06 UTC, itskatherine requested changes
Hi Asad, when we leave feedback on a PR, you need to implement the feedback on that same branch, then (if it's been approved) merge that branch to main. In between tickets you should then branch off of main. Could you please do this for all tickets going forward please 🙂 
Can you please have a look over my comments and once you've implemented them (and pushed them to this branch) resubmit this PR

2023-07-19 11:06 UTC, itskatherine commented on components/Header.jsx
> +      </section>
There's currently no way to navigate to your articles from the home page (without manually typing in the path) - I'd either have your articles on the home page or add a link/navbar

2023-07-19 11:06 UTC, itskatherine commented on util.js/util.js
> +return apiArticle.get(`/articles/${article_id}`)
I think it would be good for the information to be returned from the promise here rather than in the components, ie, adding the .then() block that takes the article off the `data` key should happen here and be returned

2023-07-19 15:32 UTC, HeatherEver commented on components/Articles.jsx
> +       props.setArticles(articles)
as Katherine said sometimes you're destructuring and sometimes you're not, like here, please use one method consistently

2023-07-19 15:34 UTC, HeatherEver commented on components/Specific_article.jsx
> +function Specific_article () {
this should be called `SpecificArticle` rather than `Sepcefic_article`

2023-07-20 08:37 UTC, B7Bprog approved these changes
Hey Asad, you've done a great work, please merge! 🎉

2023-07-20 08:37 UTC, B7Bprog commented on util.js/util.js
> +
I like the setup of your 'axios' using the baseURL property.

2023-07-20 08:37 UTC, B7Bprog commented on components/SpecificArticle.jsx
> +const {article_id} = useParams()
Nice use of the 'useParams' hook.

2023-07-20 08:38 UTC, merged