Task7- upvote articles
asazycat/ncNews pull request #9
Opened 2023-07-20 14:45 UTC by asazycat

I added the ncNews heading and shrunk the comments so they don't take up most of the space. I will add mobile responsiveness later because that might take a while for me cause I am not good with css

Plus you can upvote articles now

2023-07-20 15:22 UTC, itskatherine commented on components/Upvotes.jsx
> +   const [state,setState] = useState(false)
Please can you rename this `state` 🙏 , what is it for?

2023-07-20 15:23 UTC, itskatherine commented on components/Upvotes.jsx
> +    const {id,setVotes,votes} = props
Nice use of destructuring

2023-07-21 09:33 UTC, itskatherine requested changes
Hi Asad, going in the right direction here for sure! Have a look over my comments and can you please submit another PR once you've addressed them 🙂

2023-07-21 09:33 UTC, itskatherine commented on components/Upvotes.jsx
> +    useEffect(()=> {
The functionality needed here can be achieved in an onClick function rather than a useEffect 🔍 
We also need to make sure if the vote doesn't go through (for instance if the internet stops) and there's an error, the state is corrected to reflect this
Currently if the internet stops I can still upvote the article and I only know its stopped working when I refresh the page, have a look at the [optimistic rendering notes](https://notes.northcoders.com/courses/js-front-end/ui-behaviours-and-optimistic-rendering#error-handling) if you're stuck

2023-07-21 09:33 UTC, itskatherine commented on components/Upvotes.jsx
> + <p><button onClick={()=> {setNewVotes(newVote+1)
When we're updating state in a situation where it's important to know the previous value (like incrementing the vote) - this syntax can lead to errors
Have a look at the s[etState updater functions notes](https://notes.northcoders.com/courses/js-front-end/react-state#setstate-updater-functions) to find the correct syntax to use when updating a state like this

2023-07-21 09:33 UTC, itskatherine commented on components/Upvotes.jsx
> +    const {id,setVotes,votes} = props
Nice use of destructuring 👍

2023-07-21 10:52 UTC, B7Bprog approved these changes
Hey Asad, your voting works as it is, but please check out my comments. Otherwise it's good to go.

2023-07-21 10:52 UTC, B7Bprog commented on util.js/util.js
> + console.log(res.data.votes,"api")
Please remove this log.

2023-07-21 10:52 UTC, B7Bprog commented on components/Upvotes.jsx
> +    Upvote: </button>  {newVote} {errMsg}</p>
When voting works fine again after an error, the error message should disappear. This can be achieved with conditional rendering.

2023-07-21 11:10 UTC, merged